### ISSUE TITLE
Y variable for modelling occupancy

### ISSUE THREAD

**Issue by damianooldoni** [ToonVanDaele/trias-test#11]
Following your workflow in [`main_FULL.R`](https://github.com/ToonVanDaele/trias-test/blob/master/R/main_FULL.R), I see you analyze occupancy by applying GAM in lines [85-86](https://github.com/ToonVanDaele/trias-test/blob/master/R/main_FULL.R#L85-L86). You do by means of two functions, `spGAM_lpa_cobs` and `spGAM_lpa`.

So, reading formula used in `spGAM_lpa_cobs` and `spGAM_lpa`, I see the following (lines [118-119](https://github.com/ToonVanDaele/trias-test/blob/master/R/5c_method_GAM_short.R#L118-L119) in `5c_method_GAM_short.R`):

```r
fm <- formula(obs ~ s(year, k = maxk, m = 3, bs = "tp"))
  if (method_em == "GAM_lpa_cobs") fm <- update(fm, ~. + s(cobs))
```

Should the y-variable be `ncell` instead of `obs`? Otherwise I don't see where these formulas differ from the formulas used to model observations (lines [28-29](https://github.com/ToonVanDaele/trias-test/blob/master/R/5c_method_GAM_short.R#L28-L29)):

``` r
fm <- formula(obs ~ s(year, k = maxk, m = 3, bs = "tp"))
  if (method_em == "GAM_lcount_cobs") fm <- update(fm, ~. + s(cobs))
```

Am I right or are I missing something? Thanks.

**Comment by ToonVanDaele** [comment]
yes, it should be "ncell" instead of "obs".  It's corrected in the code
