### ISSUE TITLE
Warning message about convergence

### ISSUE THREAD

**Issue by damianooldoni** [ToonVanDaele/trias-test#8]
I get this warning while applying GAM to "lumped" data of `taxonKey` 1713034 using method `GAM_lcount_cobs`:

```r
Warning message:
In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Iteration limit reached without full convergence - check carefully
```

Is this something should we worry about it?

**Comment by ToonVanDaele** [comment]
It means the model didn't converge to meaningfull model parameters. Most probably due to poor data. Right now the algorithm will return 'unclear'. It's better to return 'NA'. I'll adapt the spGAMxxx functions

**Comment by damianooldoni** [comment]
To do this, I suggest to use tryCatch then. As up to now the try() doesn't catch any warning. See example:
```r
x <- function(i){
  if (i < 10) warning("A warning")
  i
}

tt <- tryCatch(x(5),error=function(e) e, warning=function(w) w)

tt2 <- tryCatch(x(15),error=function(e) e, warning=function(w) w)
```
More about this example in [StackOverflow link](https://stackoverflow.com/questions/3903157/how-can-i-check-whether-a-function-call-results-in-a-warning).

Doing it with a try() is also possible (see solution in same link), but we will not have a difference in output between warning and error, and the solution is quite ugly, I find.

**Comment by damianooldoni** [comment]
@ToonVanDaele : I am implementing it in this way, maybe you can find it useful:

```r
result <- tryCatch(expr = {
  model <- gam(formula = fm,
               family = nb(),
               data = df,
               method = "REML")
  }, error=function(e) e, warning=function(w) w)
#.... some other code...
if (class(result)[1] %in% c("simpleWarning", "simpleError")) {
  
} else {
}
```

**Comment by damianooldoni** [comment]
On my laptop I need tryCatch to avoid using GAM output if warning arises. Still, close this issue if you solved it.

**Comment by ToonVanDaele** [comment]
changed try to tryCatch. Works fine now. Thanks.
